name: 'Publish NPM Package'
description: 'Publish NPM Package'

runs:
  using: "composite"
  steps:

  - name: Log in to registry with NPM
    shell: bash
    run: |
      echo "@kdex:registry=https://npm.pkg.github.com" > .npmrc
      echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> .npmrc

  - name: Publish NPM package
    shell: bash
    run: |
      npm publish
